ApplayMovie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('account/', include('accounts.urls')),
    path('', include('movie.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.article_list, name='article_list'),
    path('<slug:slug>/', views.article_detail, name='article_detail'),
    path('article_comment/delete/<int:comment_id>/', views.delete_article_comment, name='delete_article_comment'),
    path('category/<slug:slug>/', views.article_category, name='article_category'),
]

core/urls.py
from django.urls import path
from . import views


app_name = 'core'
urlpatterns = [
    path('', views.home, name='home'),
    path('newsletter/', views.newsletter, name='newsletter'),
    path('contact/', views.contact, name='contact'),
]


accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.forms import ValidationError


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if len(username) > 100:
            raise ValidationError("نام کاربری نمی ‌تواند بیشتر از 100 کاراکتر باشد.")
        if User.objects.filter(username=username).exists():
            raise ValidationError("نام کاربری وارد شده از قبل وجود دارد.")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if len(email) > 100:
            raise ValidationError("ایمیل نمی ‌تواند بیشتر از 100 کاراکتر باشد.")
        if User.objects.filter(email=email).exists():
            raise ValidationError("ایمیل وارد شده از قبل وجود دارد.")
        return email

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if len(password) < 8:
            raise ValidationError("رمز عبور باید حداقل 8 کاراکتر باشد.")
        if len(password) > 20:
            raise ValidationError("رمز عبور نباید بیشتر از 20 کاراکتر باشد.")
        return password


class LoginForm(forms.Form):
    username = forms.CharField(max_length=50, widget=forms.TextInput)
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")

        if username and password:
            user = authenticate(username=username, password=password)
            if user is None:
                raise ValidationError("نام کاربری یا رمز عبور نادرست است.", code='invalid_info')

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from .forms import UserRegistrationForm, LoginForm


def user_register(request):
    if request.user.is_authenticated:
        return redirect('core:home')

    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return redirect('accounts:login')
    else:
        form = UserRegistrationForm()

    return render(request, 'accounts/register.html', {'form': form})


def user_login(request):
    if request.user.is_authenticated == True:
        return redirect('core:home')

    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            user = User.objects.get(username=form.cleaned_data.get('username'))
            login(request, user)
            return redirect('core:home')
    else:
        form = LoginForm()
    return render(request, 'accounts/login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('core:home')

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8"/>

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <!-- START: Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}"/>
    <!-- END: Favicon -->

    <!-- START: Fontawesome -->
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}"/>
    <!-- START: Fontawesome -->

    <!-- START: Style css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap-extended.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/components.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/colors.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/master.css' %}"/>
    <!-- END: Style css -->

    <!-- START: Dark Theme -->
    <link rel="stylesheet" href="{% static 'css/dark-theme/dark-layout.css' %}"/>
    <!-- END: Dark Theme -->

    <title>ورود به حساب</title>
</head>

<body>
<div id="preload">
    <div class="hm-spinner"></div>
</div>

<div id="content">
    <!-- START: Main Content -->
    <div id="login">
        <div id="main" class="col-xl-8 col-11">
            <div class="card">
                <div class="card-content">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-12 px-0">
                                <div class="card">
                                    <div class="card-header d-flex justify-content-center">
                                        <h4 class="font-weight-bolder mb-3">خوش آمدید</h4>
                                    </div>
                                    <div class="card-content">
                                        <div class="card-body">
                                            <form class="d-flex flex-column" method="post" id="login-form">
                                                {% csrf_token %}
                                                {% for error in form.non_field_errors %}
                                                    {% if error %}
                                                        <p class="alert alert-danger">{{ error }}</p>
                                                    {% endif %}
                                                {% endfor %}
                                                <div class="form-label-group form-group position-relative has-icon-left">
                                                    <input type="text" name="username" class="form-control" id="iconLabelLeft" placeholder="نام کاربری خود را وارد کنید"/>
                                                    <div class="form-control-position">
                                                        <i class="far fa-user"></i>
                                                    </div>
                                                </div>
                                                <div class="form-label-group form-group position-relative has-icon-left">
                                                    <input type="password" name="password" class="form-control" id="iconLabelLeft"
                                                           placeholder="گذرواژه خود را وارد کنید"/>
                                                    <div class="form-control-position">
                                                        <i class="far fa-key"></i>
                                                    </div>
                                                </div>
                                                <button type="submit" class="btn btn-primary glow w-100">ورود</button>
                                                <hr/>
                                                <div class="text-center">
                                                    <small class="mr-25">حساب ندارید؟</small><a
                                                        href="{% url 'accounts:register' %}"><small
                                                        class="text-primary">ثبت نام</small></a>
                                                </div>
                                                <div class="text-center mt-1">
                                                    <a href="{% url 'core:home' %}"><small class="text-dark">برگشت به صفحه اصلی</small></a>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 d-md-block d-none text-center align-self-center left-side">
                                <a href="index-2.html">
                                    <img class="card-img-top rounded" src="{% static 'img/login.svg' %}" alt="" data-tilt
                                         data-tilt-scale="1.1"/>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END: Main Content -->
</div>

<!-- START: Bootstrap -->
<script src="{% static 'js/scripts/popper.min_2.js' %}"></script>
<script src="{% static 'js/scripts/bootstrap.min.js' %}"></script>
<!-- END: Bootstrap -->

<!-- START: Js titl -->
<script src="{% static 'js/scripts/vanilla-tilt.js' %}"></script>
<!-- END: JS titl -->

<script src="{% static 'js/app.js' %}"></script>
</body>
</html>

accounts/templates/accounts/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8"/>

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <!-- START: Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}"/>
    <!-- END: Favicon -->

    <!-- START: Fontawesome -->
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}"/>
    <!-- START: Fontawesome -->

    <!-- START: Style css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap-extended.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/components.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/colors.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/master.css' %}"/>
    <!-- END: Style css -->

    <!-- START: Dark Theme -->
    <link rel="stylesheet" href="{% static 'css/dark-theme/dark-layout.css' %}"/>
    <!-- END: Dark Theme -->

    <title>ثبت نام</title>
</head>

<body>
<div id="preload">
    <div class="hm-spinner"></div>
</div>

<div id="content">
    <!-- START: Main Content -->
    <div id="login">
        <div id="main" class="col-xl-8 col-11">
            <div class="card">
                <div class="card-content">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-12 px-0">
                                <div class="card">
                                    <div class="card-header d-flex justify-content-center">
                                        <h4 class="font-weight-bolder mb-2">خوش آمدید</h4>
                                    </div>
                                    <div class="card-content">
                                        <div class="card-body">
                                            <form class="d-flex flex-column" method="post" id="login-form">
                                                {% csrf_token %}
                                                {% for error_username in form.username.errors %}
                                                    {% if error_username %}
                                                        <p class="alert alert-danger">{{ error_username }}</p>
                                                    {% endif %}
                                                {% endfor %}
                                                <div class="form-label-group form-group position-relative has-icon-left">
                                                    <input type="text" name="username" class="form-control" id="iconLabelLeft" placeholder="نام کاربری خود را وارد کنید"/>
                                                    <div class="form-control-position">
                                                        <i class="far fa-user"></i>
                                                    </div>
                                                </div>
                                                {% for error_email in form.email.errors %}
                                                    {% if error_email %}
                                                        <p class="alert alert-danger">{{ error_email }}</p>
                                                    {% endif %}
                                                {% endfor %}
                                                <div class="form-label-group form-group position-relative has-icon-left">
                                                    <input type="text" name="email" class="form-control" id="iconLabelLeft" placeholder="ایمیل خود را وارد کنید"/>
                                                    <div class="form-control-position">
                                                        <i class="far fa-envelope"></i>
                                                    </div>
                                                </div>
                                                {% for error_password in form.password.errors %}
                                                    {% if error_password %}
                                                        <p class="alert alert-danger">{{ error_password }}</p>
                                                    {% endif %}
                                                {% endfor %}
                                                <div class="form-label-group form-group position-relative has-icon-left">
                                                    <input type="password" name="password" class="form-control" id="iconLabelLeft" placeholder="گذرواژه خود را وارد کنید"/>
                                                    <div class="form-control-position">
                                                        <i class="far fa-key"></i>
                                                    </div>
                                                </div>
                                                <button type="submit" class="btn btn-primary glow w-100">
                                                    ثبت نام
                                                </button>
                                                <hr/>
                                                <div class="text-center">
                                                    <small class="mr-25">حساب دارید؟</small><a
                                                        href="{% url 'accounts:login' %}"><small
                                                        class="text-primary">ورود</small></a>
                                                </div>
                                                <div class="text-center mt-1">
                                                    <a href="{% url 'core:home' %}"><small class="text-dark">برگشت به صفحه اصلی</small></a>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 d-md-block d-none text-center align-self-center left-side">
                                <a href="index-2.html">
                                    <img class="card-img-top rounded" src="{% static 'img/signup.svg' %}" alt="" data-tilt
                                         data-tilt-scale="1.1"/>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END: Main Content -->
</div>

<!-- START: Bootstrap -->
<script src="{% static 'js/scripts/popper.min_2.js' %}"></script>
<script src="{% static 'js/scripts/bootstrap.min.js' %}"></script>
<!-- END: Bootstrap -->

<!-- START: Js titl -->
<script src="{% static 'js/scripts/vanilla-tilt.js' %}"></script>
<!-- END: JS titl -->

<script src="{% static 'js/app.js' %}"></script>
</body>


<!-- Mirrored from applay.cfarhad.ir/signup.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 19 Dec 2024 04:03:49 GMT -->
</html>