ApplayMovie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('account/', include('accounts.urls')),
    path('', include('movie.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.article_list, name='article_list'),
    path('<slug:slug>/', views.article_detail, name='article_detail'),
    path('article_comment/delete/<int:comment_id>/', views.delete_article_comment, name='delete_article_comment'),
    path('category/<slug:slug>/', views.article_category, name='article_category'),
]

movie/urls.py
from django.urls import path
from . import views


app_name = 'movie'
urlpatterns = [
    path('movies/', views.movies_list, name='movies_list'),
    path('movies/<slug:slug>/', views.movie_detail, name='movie_detail'),
    path('movie_comment/delete/<int:comment_id>/', views.delete_movie_comment, name='delete_movie_comment'),
    path('series/', views.series_list, name='series_list'),
    path('series/<slug:slug>/', views.series_detail, name='series_detail'),
    path('series_comment/delete/<int:comment_id>/', views.delete_series_comment, name='delete_series_comment'),
    path('genres/', views.genre_list, name='genre_list'),
    path('genre/movies/<slug:slug>/', views.genre_movies, name='genre_movies'),
    path('genre/series/<slug:slug>/', views.genre_series, name='genre_series'),
    path('actors/', views.actors_list, name='actors_list'),
    path('actors/<slug:slug>/', views.actor_detail, name='actor_detail'),
    path('search/', views.search, name='search'),
    path('actor_search/', views.actor_search, name='actor_search'),
]

templates/includes/blog_sidebar.html
{% load static %}
{% load jalali_tags %}
<div class="col-xl-3 col-lg-4 col-md-12 col-sm-12" id="sidebar">
    <div>
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12">
                                <ul class="nav nav-pills justify-content-center">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="base-pill31" data-toggle="pill" href="#pill31"
                                           aria-expanded="true">
                                            بروز شده ها
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="base-pill32" data-toggle="pill" href="#pill32"
                                           aria-expanded="false">
                                            پر بازدید ترین
                                        </a>
                                    </li>
                                </ul>
                                <div class="tab-content shadow-none">
                                    <div role="tabpanel" class="tab-pane active" id="pill31"> <!--بروز شده-->
                                        {% for article in updated_articles %}
                                            <a href="{% url 'blog:article_detail' article.slug %}">
                                                <div class="d-flex border-bottom pb-1 mt-1">
                                                    {% if article.thumbnail %}
                                                        <img class="rounded mr-1" src="{{ article.thumbnail.url }}"
                                                             height="70" width="70" alt="{{ article.title|truncatewords:6 }}"/>
                                                    {% else %}
                                                        <img class="rounded mr-1"
                                                             src="{% static 'img/category_image_not_available.jpg' %}"
                                                             height="70" width="70" alt="{{ article.title|truncatewords:6 }}"/>
                                                    {% endif %}
                                                    <div>
                                                        <a href="{% url 'blog:article_detail' article.slug %}">
                                                            <h6>{{ article.title|truncatewords:6 }}</h6>
                                                        </a>
                                                        <span class="font-size-small">{{ article.created_at|to_jalali:'%Y/%m/%d' }}</span>
                                                    </div>
                                                </div>
                                            </a>
                                        {% endfor %}
                                    </div>
                                    <div class="tab-pane" id="pill32">
                                        {% for article in popular_articles %}
                                            <a href="{% url 'blog:article_detail' article.slug %}">
                                                <div class="d-flex border-bottom pb-1 mt-1">
                                                    {% if article.thumbnail %}
                                                        <img class="rounded mr-1" src="{{ article.thumbnail.url }}" height="70" width="70" alt="{{ article.title|truncatewords:6 }}"/>
                                                    {% else %}
                                                        <img class="rounded mr-1" src="{% static 'img/category_image_not_available.jpg' %}" height="70" width="70" alt="{{ article.title|truncatewords:6 }}"/>
                                                    {% endif %}
                                                    <div>
                                                        <a href="{% url 'blog:article_detail' article.slug %}">
                                                            <h6>{{ article.title|truncatewords:6 }}</h6>
                                                        </a>
                                                        <span class="font-size-small">{{ article.created_at|to_jalali:'%Y/%m/%d' }}</span>
                                                    </div>
                                                </div>
                                            </a>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/includes/movie_sidebar.html
{% load static %}
<div class="col-xl-3 col-lg-4 col-md-12 col-sm-12" id="sidebar">
    <div>
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="title">ژانر فیلم ها</h5>
                        <div class="row">
                            {% for genre in genres_movies %}
                                <div class="col-6">
                                    <a href="{% url 'movie:genre_movies' genre.slug %}">
                                        <div class="category">
                                            <p>{{ genre.title }}</p>
                                            <span>{{ genre.movies_genre.count }}</span>
                                        </div>
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-12 col-lg-12 col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="title">ژانر سریال ها</h5>
                        <div class="row">
                            {% for genre in genres_series %}
                                <div class="col-6">
                                    <a href="{% url 'movie:genre_series' genre.slug %}">
                                        <div class="category">
                                            <p>{{ genre.title }}</p>
                                            <span>{{ genre.series_genre.count }}</span>
                                        </div>
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-12 col-lg-12 col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="title">بروز شده ها</h5>
                        <div class="col-12">
                            <a href="#">
                                <div class="update">
                                    <img
                                            class="update-img"
                                            src="{% static 'img/series/flash.jpg' %}"
                                            alt=""
                                    />
                                    <div class="update-body">
                                        <h6>قسمت 1 از فصل 1</h6>
                                    </div>
                                </div>
                            </a>
                            <a href="#">
                                <div class="update">
                                    <img
                                            class="update-img"
                                            src="{% static 'img/series/arrow.jpg' %}"
                                            alt=""
                                    />
                                    <div class="update-body">
                                        <h6>قسمت 2 از فصل 3</h6>
                                    </div>
                                </div>
                            </a>
                            <a href="#">
                                <div class="update">
                                    <img
                                            class="update-img"
                                            src="{% static 'img/series/breaking_bad.jpg' %}"
                                            alt=""
                                    />
                                    <div class="update-body">
                                        <h6>قسمت 5 از فصل 3</h6>
                                    </div>
                                </div>
                            </a>
                            <a href="#">
                                <div class="update">
                                    <img
                                            class="update-img"
                                            src="{% static 'img/series/money_heist.jpg' %}"
                                            alt=""
                                    />
                                    <div class="update-body">
                                        <h6>قسمت 3 از فصل 2</h6>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-12 col-lg-12 col-md-6 col-sm-12">
                <div
                        class="card shadow-none d-flex align-items-center justify-content-center py-4 bg-primary"
                >
                    <img class="" src="{% static 'img/svg/box.svg' %}" alt="" height="100"/>
                    <h6 class="text-white text-center">
                        محل تبلیغ شما اینجاست !
                    </h6>
                </div>
                <div
                        class="card shadow-none align-items-center justify-content-center py-4 bg-primary d-lg-none d-md-flex"
                >
                    <img class="" src="{% static 'img/svg/box.svg' %}" alt="" height="100"/>
                    <h6 class="text-white text-center">
                        محل تبلیغ شما اینجاست !
                    </h6>
                </div>
            </div>
        </div>
    </div>
</div>