ApplayMovie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('account/', include('accounts.urls')),
    path('', include('movie.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.article_list, name='article_list'),
    path('<slug:slug>/', views.article_detail, name='article_detail'),
    path('article_comment/delete/<int:comment_id>/', views.delete_article_comment, name='delete_article_comment'),
    path('category/<slug:slug>/', views.article_category, name='article_category'),
]

core/urls.py
from django.urls import path
from . import views


app_name = 'core'
urlpatterns = [
    path('', views.home, name='home'),
    path('newsletter/', views.newsletter, name='newsletter'),
    path('contact/', views.contact, name='contact'),
]


movie/urls.py
from django.urls import path
from . import views


app_name = 'movie'
urlpatterns = [
    path('movies/', views.movies_list, name='movies_list'),
    path('movies/<slug:slug>/', views.movie_detail, name='movie_detail'),
    path('movie_comment/delete/<int:comment_id>/', views.delete_movie_comment, name='delete_movie_comment'),
    path('series/', views.series_list, name='series_list'),
    path('series/<slug:slug>/', views.series_detail, name='series_detail'),
    path('series_comment/delete/<int:comment_id>/', views.delete_series_comment, name='delete_series_comment'),
    path('genres/', views.genre_list, name='genre_list'),
    path('genre/movies/<slug:slug>/', views.genre_movies, name='genre_movies'),
    path('genre/series/<slug:slug>/', views.genre_series, name='genre_series'),
    path('actors/', views.actors_list, name='actors_list'),
    path('actors/<slug:slug>/', views.actor_detail, name='actor_detail'),
    path('search/', views.search, name='search'),
    path('actor_search/', views.actor_search, name='actor_search'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8"/>

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <!-- START: Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}"/>
    <!-- END: Favicon -->

    <!-- START: Swiper css -->
    <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}"/>
    <!-- END: Swiper css -->

    <!-- START: Fontawesome -->
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}"/>
    <!-- START: Fontawesome -->

    <!-- START: Style css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap-extended.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/components.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/colors.css' %}" />
    <link rel="stylesheet" href="{% static 'css/master.css' %}"/>
    <!-- END: Style css -->

    <!-- START: Dark Theme -->
    <link rel="stylesheet" href="{% static 'css/dark-theme/dark-layout.css' %}"/>

    <!-- END: Dark Theme -->

    <title>{% block title %}{% endblock %}</title>
</head>

<body class="">
<div id="preload">
    <div class="hm-spinner"></div>
</div>

<div id="content">
    <!-- START: Main menu -->
    <div class="w-100" id="backMain">
        <div class="container-fluid container-lg">
            <div class="navbar navbar-expand-lg px-0">
                <a href="{% url 'core:home' %}" class="navbar-brand" id="logo">
                    <img src="{% static 'img/logo.png' %}" alt=""/>
                </a>
                <button class="navbar-toggler" data-toggle="collapse" data-target="#navbar-nav">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbar-nav">
                    <ul class="navbar-nav">
                        <li class="nav-item mx-2 my-1 mx-0">
                            <a href="{% url 'core:home' %}" class="nav-item text-dark">خانه</a>
                        </li>
                        <li class="nav-item mx-2 my-1">
                            <a href="{% url 'movie:movies_list' %}" class="nav-item text-dark">فیلم</a>
                        </li>
                        <li class="nav-item mx-2 my-1">
                            <a href="{% url 'movie:series_list' %}" class="nav-item text-dark">سریال</a>
                        </li>
                        <li class="nav-item mx-2 my-1">
                            <a href="{% url 'movie:genre_list' %}" class="nav-item text-dark">ژانر ها</a>
                        </li>
                        <li class="nav-item mx-2 my-1">
                            <a href="{% url 'movie:actors_list' %}" class="nav-item text-dark">بازیگران</a>
                        </li>
                        <li class="nav-item mx-2 my-1">
                            <a href="{% url 'blog:article_list' %}" class="nav-item text-dark">وبلاگ</a>
                        </li>
                        <li class="nav-item mx-2 my-1">
                            <a href="{% url 'core:contact' %}" class="nav-item text-dark">تماس با ما</a>
                        </li>
                        <li class="nav-item mx-2 my-1">
                            {% if request.user.is_authenticated %}
                                <span class="nav-item text-dark">{{ request.user.username }}</span> |
                                <a href="{% url 'accounts:logout' %}" class="nav-item text-dark">خروج</a>
                            {% else %}
                                <a href="{% url 'accounts:login' %}" class="nav-item text-dark">ثبت نام / ورود</a>
                            {% endif %}
                        </li>
                    </ul>
                    <form class="ml-auto w-25" method="get" action="{% url 'movie:search' %}">
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" value="{{ request.GET.q }}" placeholder="فیلم یا سریال مدنظر + اینتر" id="searchBox"/>
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-primary">
                                    <i class="far fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- END: Main menu -->

    <!-- START: Submenu -->
    <div
            class="w-100 bg-transparent border-bottom border-top d-none d-md-block" id="navbar-children">
        <div class="container-fluid container-lg px-0">
            <ul class="nav p-1">
                {% for serial in popular_series %}
                    <li class="nav-item mx-1 font-small-3">
                        <a href="{% url 'movie:series_detail' serial.slug %}" class="text-dark">{{ serial.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <!-- END: Submenu -->

    {% block content %}{% endblock %}

    <!-- START: Footer -->
    <div class="w-100 bg-white" id="social_media">
        <div class="container container-lg">
            <div class="d-flex align-items-center justify-content-between social_main">
                <h6 class="d-lg-block d-sm-block d-none text-dark font-weight-bolder p-0 m-0">ما را در شبکه های اجتماعی دنبال کنید</h6>
                <div class="d-flex align-items-center">
                    {% if site_settings.telegram_link %}
                        <a class="font-medium-4 mx-1 text-dark" href="{{ site_settings.telegram_link }}">
                            <i class="fab fa-telegram"></i>
                        </a>
                    {% endif %}
                    {% if site_settings.instagram_link %}
                        <a class="font-medium-4 mx-1 text-dark" href="{{ site_settings.instagram_link }}">
                            <i class="fab fa-instagram"></i>
                        </a>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
    <div class="bg-white" id="footer">
        <div class="container container-lg">
            <div class="row">
                <div class="col-lg-4 col-md-6 col-12">
                    <img width="200" src="{% static 'img/logo.png' %}" alt="">
                    <div>
                        {% if site_settings.address %}
                            <div class="my-1">
                                <i class="fas fa-map-marker-alt text-light"></i>
                                <span class="ml-1 text-light">{{ site_settings.address }}</span>
                            </div>
                        {% endif %}
                        {% if site_settings.phone %}
                            <div class="my-1">
                                <i class="fas fa-phone-alt text-light"></i>
                                <span class="text-light ml-1">شماره تماس : </span>
                                <span class="text-light">{{ site_settings.phone }}</span>
                            </div>
                        {% endif %}
                        {% if site_settings.email %}
                            <div class="my-1">
                                <i class="fas fa-at text-light"></i>
                                <span class="text-light ml-1">{{ site_settings.email }}</span>
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-12">
                    <h3 class="font-weight-bolder text-dark">فیلم ها</h3>
                    <ul class="list-unstyled">
                        {% for movie in popular_movies %}
                            <li class="mb-1"><a class="text-light" href="{% url 'movie:movie_detail' movie.slug %}">{{ movie.title }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-lg-2 col-md-6 col-12">
                    <h3 class="font-weight-bolder text-dark">سریال ها</h3>
                    <ul class="list-unstyled">
                        {% for serial in popular_series %}
                            <li class="mb-1"><a class="text-light" href="{% url 'movie:series_detail' serial.slug %}">{{ serial.title }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-lg-4 col-md-6 col-12 mt-1">
                    <h6 class="text-light">در خبرنامه ما عضو شوید تا از محتوای جدید بهره مند شوید</h6>
                    <form class="ml-auto w-100" action="{% url 'core:newsletter' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" name="email" id="email" class="form-control" placeholder="آدرس ایمیل را وارد کنید" required/>
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-primary">عضویت</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="mt-3" id="sub_footer">
            <div class="p-1 d-flex align-items-center">
                <p class="p-0 m-0 text-center w-100">&copy; {{ site_settings.copy_right }}</p>
            </div>
        </div>
    </div>
    <div class="container-fluid container-lg">
        <div class="main_gotop">
            <a class="goTop" href="JavaScript:void(0)">
                <i class="fas fa-angle-up"></i>
            </a>
        </div>
    </div>
    <!-- END: Footer -->
</div>

<!-- START: Bootstrap -->
<script src="{% static 'js/scripts/popper.min_2.js' %}"></script>
<script src="{% static 'js/scripts/bootstrap.min.js' %}"></script>
<!-- END: Bootstrap -->

<!-- START: Swiper JS -->
<script src="{% static 'js/scripts/swiper-bundle.min.js' %}"></script>
<!-- END: Swiper JS -->

<!-- START: Swiper options -->
<script src="{% static 'js/swiperOptions.js' %}"></script>
<!-- END: Swiper options -->

<!-- START: Sweetalert 2 -->
<script src="{% static 'js/scripts/sweetalert.min.js' %}"></script>
<!-- START: Sweetalert 2 -->

<!-- START: Sweetalert 2 options -->
<script src="{% static 'js/sweetalertOptions.js' %}"></script>
<!-- END: Sweetalert 2 options -->

<!-- START: Js titl -->
<script src="{% static 'js/scripts/vanilla-tilt.js' %}"></script>
<!-- END: JS titl -->

<script src="{% static 'js/app.js' %}"></script>
</body>

</html>