ApplayMovie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('account/', include('accounts.urls')),
    path('', include('movie.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.article_list, name='article_list'),
    path('<slug:slug>/', views.article_detail, name='article_detail'),
    path('article_comment/delete/<int:comment_id>/', views.delete_article_comment, name='delete_article_comment'),
    path('category/<slug:slug>/', views.article_category, name='article_category'),
]

movie/urls.py
from django.urls import path
from . import views


app_name = 'movie'
urlpatterns = [
    path('movies/', views.movies_list, name='movies_list'),
    path('movies/<slug:slug>/', views.movie_detail, name='movie_detail'),
    path('movie_comment/delete/<int:comment_id>/', views.delete_movie_comment, name='delete_movie_comment'),
    path('series/', views.series_list, name='series_list'),
    path('series/<slug:slug>/', views.series_detail, name='series_detail'),
    path('series_comment/delete/<int:comment_id>/', views.delete_series_comment, name='delete_series_comment'),
    path('genres/', views.genre_list, name='genre_list'),
    path('genre/movies/<slug:slug>/', views.genre_movies, name='genre_movies'),
    path('genre/series/<slug:slug>/', views.genre_series, name='genre_series'),
    path('actors/', views.actors_list, name='actors_list'),
    path('actors/<slug:slug>/', views.actor_detail, name='actor_detail'),
    path('search/', views.search, name='search'),
    path('actor_search/', views.actor_search, name='actor_search'),
]

movie/models.py
from django.db import models
from django.contrib.auth.models import User
import os


GENDER = (
    ("man", "مرد"),
    ("woman", "زن"),
)

STATUS = (
    ("draft", "پیش نویس شود"),
    ("published", "منتشر شود"),
)


class Genre(models.Model):
    title = models.CharField(max_length=100, unique=True, verbose_name='عنوان ژانر')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='نامک')
    thumbnail = models.ImageField(upload_to='genre_thumbnails/', null=True, blank=True, verbose_name='تصویر ژانر')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')

    class Meta:
        verbose_name = 'ژانر'
        verbose_name_plural = 'ژانر ها'

    def __str__(self):
        return self.title


class Language(models.Model):
    name = models.CharField(max_length=50, verbose_name='زبان')

    class Meta:
        verbose_name = 'زبان'
        verbose_name_plural = 'زبان ها'

    def __str__(self):
        return self.name


class Actor(models.Model):
    name = models.CharField(max_length=200, unique=True, verbose_name='اسم بازیگر')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='نامک')
    description = models.TextField(verbose_name='درباره بازیگر')
    thumbnail = models.ImageField(upload_to='actor_thumbnails/', null=True, blank=True, verbose_name='تصویر بازیگر')
    gender = models.CharField(choices=GENDER, max_length=10, default='man', verbose_name='جنسیت')
    date_birth = models.DateField(verbose_name='تاریخ تولد')
    place_birth = models.CharField(max_length=300, verbose_name='محل تولد')
    views = models.IntegerField(default=0, verbose_name='بازدید ها')
    status = models.CharField(choices=STATUS, max_length=10, default='published', verbose_name='وضعیت')

    class Meta:
        verbose_name = 'بازیگر'
        verbose_name_plural = 'بازیگران'

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=200, unique=True, verbose_name='عنوان فیلم')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='نامک')
    genre = models.ManyToManyField(Genre, related_name='movies_genre', verbose_name='ژانر')
    language = models.ManyToManyField(Language, related_name='movies_language', verbose_name='زبان فیلم')
    description = models.TextField(verbose_name='خلاصه داستان')
    thumbnail = models.ImageField(upload_to='movie_thumbnails/', null=True, blank=True, verbose_name='تصویر فیلم')
    actors = models.ManyToManyField(Actor, related_name='movies', verbose_name='بازیگران')
    similar_movies = models.ManyToManyField('self', blank=True, null=True, related_name='similar', verbose_name='فیلم های مشابه')
    country = models.CharField(max_length=300, verbose_name='کشور سازنده')
    director = models.CharField(max_length=200, verbose_name='اسم کارگردان')
    duration = models.CharField(max_length=5, verbose_name='مدت زمان فیلم (لطفاً مدت زمان را به دقیقه وارد کنید)')
    release_date = models.DateField(verbose_name='تاریخ انتشار')
    score = models.CharField(max_length=10, default='0.0/10', verbose_name='امتیاز')
    age_range = models.CharField(max_length=20, default='بالای 14 سال', verbose_name='رنج سنی')
    views = models.IntegerField(default=0, verbose_name='بازدید ها')
    trailer = models.URLField(max_length=500, verbose_name='لینک تریلر فیلم')
    subtitle_url = models.URLField(max_length=500, blank=True, null=True, verbose_name='لینک زیرنویس فیلم')
    quality_480p = models.URLField(verbose_name='لینک کیفیت 480p', blank=True, null=True)
    quality_720p = models.URLField(verbose_name='لینک کیفیت 720p', blank=True, null=True)
    quality_1080p = models.URLField(verbose_name='لینک کیفیت 1080p', blank=True, null=True)
    is_recommended = models.BooleanField(default=False, verbose_name='آیا فیلم، پیشنهادی است؟')
    status = models.CharField(choices=STATUS, max_length=10, default='published', verbose_name='وضعیت')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='تاریخ به‌روزرسانی')

    class Meta:
        verbose_name = 'فیلم'
        verbose_name_plural = 'فیلم ها'

    def formatted_release_date(self):
        return self.release_date.strftime('%Y/%m/%d')

    def __str__(self):
        return self.title


def movie_image_upload_to(instance, filename):
    movie_slug = instance.movie.slug
    folder_name = f"movie_images/{movie_slug}/"
    return os.path.join(folder_name, filename)


class MovieImage(models.Model):
    movie = models.ForeignKey(Movie, related_name="movie_images", on_delete=models.CASCADE, verbose_name='فیلم مربوطه')
    images = models.ImageField(upload_to=movie_image_upload_to, null=True, blank=True, verbose_name='اسکرین شات فیلم')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')

    class Meta:
        verbose_name = "تصویر فیلم"
        verbose_name_plural = "تصاویر فیلم ها"


class Series(models.Model):
    title = models.CharField(max_length=200, unique=True, verbose_name='عنوان سریال')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='نامک')
    genre = models.ManyToManyField(Genre, related_name='series_genre', verbose_name='ژانر')
    language = models.ManyToManyField(Language, related_name='series_language', verbose_name='زبان سریال')
    description = models.TextField(verbose_name='خلاصه داستان')
    thumbnail = models.ImageField(upload_to='series_thumbnails/', null=True, blank=True, verbose_name='تصویر سریال')
    actors = models.ManyToManyField(Actor, related_name='series', verbose_name='بازیگران')
    similar_series = models.ManyToManyField('self', blank=True, null=True, related_name='similar', verbose_name='سریال های مشابه')
    country = models.CharField(max_length=300, verbose_name='کشور سازنده')
    director = models.CharField(max_length=200, verbose_name='اسم کارگردان')
    duration = models.CharField(max_length=5, verbose_name='مدت زمان سریال (لطفاً مدت زمان را به دقیقه وارد کنید)')
    chapter_count = models.PositiveIntegerField(verbose_name='تعداد فصل ها')
    release_date = models.DateField(verbose_name='تاریخ انتشار')
    score = models.CharField(max_length=10, default='0.0/10', verbose_name='امتیاز')
    age_range = models.CharField(max_length=20, default='بالای 14 سال', verbose_name='رنج سنی')
    views = models.IntegerField(default=0, verbose_name='بازدید ها')
    trailer = models.URLField(max_length=500, verbose_name='لینک تریلر سریال')
    subtitle_url = models.URLField(max_length=500, blank=True, null=True, verbose_name='لینک زیرنویس سریال')
    status = models.CharField(choices=STATUS, max_length=10, default='published', verbose_name='وضعیت')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='تاریخ به‌روزرسانی')

    class Meta:
        verbose_name = 'سریال'
        verbose_name_plural = 'سریال ها'

    def formatted_release_date(self):
        return self.release_date.strftime('%Y/%m/%d')

    def __str__(self):
        return self.title


def series_image_upload_to(instance, filename):
    series_slug = instance.series.slug
    folder_name = f"series_images/{series_slug}/"
    return os.path.join(folder_name, filename)


class SeriesImage(models.Model):
    series = models.ForeignKey(Series, related_name="series_images", on_delete=models.CASCADE, verbose_name='سریال مربوطه')
    images = models.ImageField(upload_to=series_image_upload_to, null=True, blank=True, verbose_name='اسکرین شات سریال')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')

    class Meta:
        verbose_name = "تصویر سریال"
        verbose_name_plural = "تصاویر سریال ها"


class ChapterSeries(models.Model):
    series = models.ForeignKey(Series, on_delete=models.CASCADE, verbose_name='سریال مربوطه')
    title = models.CharField(max_length=150, unique=True, verbose_name='عنوان فصل')
    order = models.PositiveIntegerField(verbose_name='ترتیب فصل')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='تاریخ به‌روزرسانی')

    class Meta:
        verbose_name = 'فصل سریال'
        verbose_name_plural = 'فصل های سریال'

    def __str__(self):
        return self.title


class VideoSeries(models.Model):
    chapter = models.ForeignKey(ChapterSeries, on_delete=models.CASCADE, verbose_name='فصل مربوطه')
    quality_480p = models.URLField(verbose_name='لینک کیفیت 480p', blank=True, null=True)
    quality_720p = models.URLField(verbose_name='لینک کیفیت 720p', blank=True, null=True)
    quality_1080p = models.URLField(verbose_name='لینک کیفیت 1080p', blank=True, null=True)
    order = models.PositiveIntegerField(verbose_name='ترتیب ویدیو')

    class Meta:
        verbose_name = 'ویدیو سریال'
        verbose_name_plural = 'ویدیو های سریال'

    def __str__(self):
        return self.chapter.title


class MovieComment(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='movie_comments', verbose_name='فیلم مربوطه')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='movie_comments', verbose_name='نویسنده نظر')
    body = models.TextField(verbose_name='متن نظر')
    status = models.CharField(choices=STATUS, max_length=10, default='published', verbose_name='وضعیت')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')

    class Meta:
        verbose_name = 'نظر فیلم'
        verbose_name_plural = 'نظرات فیلم ها'

    def __str__(self):
        return self.movie.title


class SeriesComment(models.Model):

movie/templates/movie/actor_detail.html
{% extends 'base.html' %}
{% block title %}بازیگران{% endblock %}
{% load static %}

{% block content %}
    <!-- START: Main -->
    <div class="container container-lg mt-5">
        <div class="row">
            <div class="col-lg-3 col-md-4 col-sm-12 col-12">
                <div class="card h-100">
                    <div class="card-body">
                        {% if actors.thumbnail %}
                            <img class="w-100 h-100 rounded" src="{{ actors.thumbnail.url }}" alt="{{ actors.name }}"/>
                        {% else %}
                            <img class="w-100 h-100 rounded" src="{% static 'img/image_not_available.jpg' %}"
                                 alt="{{ actors.name }}"/>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-8 col-sm-12 col-12 d-flex justify-content-between flex-column">
                <div class="card p-1 mb-0">
                    <div class="card-about">
                        <h4 class="text-dark font-weight-bolder">{{ actors.name }}</h4>
                        <h6>{{ actors.description }}</h6>
                    </div>
                    <div class="card-footer p-0">
                        <h5 class="text-dark">حضور داشته در :</h5>
                        <div class="swiper-container swiper-container3 swip">
                            <!-- Additional required wrapper -->
                            <div class="swiper-wrapper">
                                <!-- Slides -->
                                {% for item in items %}
                                    <div class="swiper-slide card hover mb-0">
                                        {% if item.thumbnail %}
                                            <img class="card-img-top" src="{{ item.thumbnail.url }}"
                                                 alt="{{ item.title }}"/>
                                        {% else %}
                                            <img class="card-img-top" src="{% static 'img/image_not_available.jpg' %}"
                                                 alt="{{ item.title }}"/>
                                        {% endif %}
                                        <div class="card-body">
                                            <div class="card-content">
                                                <a href="

                                                        {% if item.chapter_count %}{% url 'movie:series_detail' item.slug %}{% else %}{% url 'movie:movie_detail' item.slug %}{% endif %}"
                                                   class="card-link">
                                                    <h5>{{ item.title }}</h5>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <!-- If we need pagination -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-5 col-sm-12 col-12 mt-2">
                <div class="card">
                    <div class="card-header">
                        <h5 class="title font-weight-bolder text-dark">جزئیات</h5>
                    </div>
                    <div class="card-body">
                        <div>
                            <h6>
                                <span>به عنوان : </span>
                                <span class="font-weight-bolder">بازیگر</span>
                            </h6>
                            <h6>
                                <span>فیلم های بازی شده : </span>
                                <span class="font-weight-bolder">{{ movies.count }}</span>
                            </h6>
                            <h6>
                                <span>سریال های بازی شده : </span>
                                <span class="font-weight-bolder">{{ series.count }}</span>
                            </h6>
                            <h6>
                                <span>جنسیت : </span>
                                <span class="font-weight-bolder">{{ actors.get_gender_display }}</span>
                            </h6>
                            <h6>
                                <span>تاریخ تولد : </span>
                                <span class="font-weight-bolder">{{ actors.date_birth }}</span>
                            </h6>
                            <h6>
                                <span>محل تولد : </span>
                                <span class="font-weight-bolder">{{ actors.place_birth }}</span>
                            </h6>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-8 col-sm-12 col-12 mt-2">
                <div class="card">
                    <div class="card-header">
                        <h5 class="text-dark title font-weight-bolder">تمام فیلم ها</h5>
                    </div>
                    <div class="card-body">
                        {% if movies %}
                            {% for movie in movies %}
                                <h6 class="muted">
                                    <i class="far fa-camera-movie"></i>
                                    <a class="text-muted ml-1"
                                       href="{% url 'movie:movie_detail' movie.slug %}">{{ movie.title }}</a>
                                </h6>
                            {% endfor %}
                        {% else %}
                            <h6 class="muted">
                                <a class="text-muted ml-1">هیچ فیلمی وجود ندارد!</a>
                            </h6>
                        {% endif %}
                    </div>
                    <div class="card-header">
                        <h5 class="text-dark title font-weight-bolder">تمام سریال ها</h5>
                    </div>
                    <div class="card-body">
                        {% if series %}
                            {% for serial in series %}
                                <h6 class="muted">
                                    <i class="far fa-camera-movie"></i>
                                    <a class="text-muted ml-1"
                                       href="{% url 'movie:series_detail' serial.slug %}">{{ serial.title }}</a>
                                </h6>
                            {% endfor %}
                        {% else %}
                            <h6 class="muted">
                                <a class="text-muted ml-1">هیچ سریالی وجود ندارد!</a>
                            </h6>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END: Main -->

    <!-- START:Theme option -->
    <div class="shadow p-2 customizer" id="theme-option">
        <div class="change-setting shadow cursor-pointer">
            <a href="#" class="font-medium-4">
                <i class="fas fa-cog"></i>
            </a>
        </div>
        <header class="d-flex align-items-center justify-content-between">
            <h4 class="font-weight-normal">تنظیمات قالب</h4>
            <a class="text-dark font-medium-4 close" href="#">
                <i class="far fa-times"></i>
            </a>
        </header>
        <hr/>
        <h5 class="mt-2">طرح قالب</h5>
        <div class="d-flex align-items-center">
            <div class="mr-1">
                <fieldset>
                    <div class="radio">
                        <input
                                type="radio"
                                name="layoutOptions"
                                value="false"
                                id="radio-light"
                                class="layout-name"
                                theme="light"
                                checked=""
                        />
                        <label for="radio-light">روشن</label>
                    </div>
                </fieldset>
            </div>
            <div class="mx-1">
                <fieldset>
                    <div class="radio">
                        <input
                                type="radio"
                                name="layoutOptions"
                                value="false"
                                id="radio-dark"
                                class="layout-name"
                                theme="dark"
                        />
                        <label for="radio-dark">تیره</label>
                    </div>
                </fieldset>
            </div>
        </div>
        <hr/>
        <div class="d-flex align-items-center justify-content-between">
            <h5 class="mt-2">سایه کارت</h5>
            <div class="custom-control custom-switch">
                <input
                        type="checkbox"
                        class="custom-control-input"
                        id="card-shadow"
                        checked
                />
                <label class="custom-control-label" for="card-shadow"></label>
            </div>
        </div>
        <hr/>
        <div class="d-flex align-items-center justify-content-between">
            <h5 class="mt-2">اسکرول به بالا</h5>
            <div class="custom-control custom-switch">
                <input
                        type="checkbox"
                        class="custom-control-input"
                        id="scroll-top"
                        name="scrollTopShow"
                        checked
                />
                <label class="custom-control-label" for="scroll-top"></label>
            </div>
        </div>
        <hr/>
        <div class="d-flex align-items-center justify-content-between">
            <h5 class="mt-2">تمام صفحه</h5>
            <div class="custom-control custom-switch">
                <input
                        type="checkbox"
                        class="custom-control-input"
                        id="fullscreen-option"
                        name="fullscrenn"
                />
                <label class="custom-control-label" for="fullscreen-option"></label>
            </div>
        </div>
        <hr/>
        <h5 class="mt-2">نوع فوتر</h5>
        <div class="d-flex align-items-center">
            <div class="mr-1">
                <fieldset>
                    <div class="radio">
                        <input
                                type="radio"
                                name="footer-option"
                                value="false"
                                class="footer-option"
                                footer="hidden"
                                id="hidden-footer"
                        />
                        <label for="hidden-footer">مخفی</label>
                    </div>
                </fieldset>
            </div>
            <div class="mx-1">
                <fieldset>
                    <div class="radio">
                        <input
                                type="radio"
                                name="footer-option"
                                value="true"
                                class="footer-option"
                                footer="static"
                                id="static-footer"
                                checked
                        />
                        <label for="static-footer">ایستا</label>
                    </div>
                </fieldset>
            </div>
            <div class="mx-1">
                <fieldset>
                    <div class="radio">
                        <input
                                type="radio"
                                name="footer-option"
                                value="false"
                                class="footer-option"
                                id="sticky-footer"
                                footer="sticky"
                        />
                        <label for="sticky-footer">چسبان</label>
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
    <!-- END:Theme option -->
{% endblock %}